author/models.py
from application import db


class Author(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(128))
    confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime, nullable=True)

    def __init__(self, username, email, password, confirmed, confirmed_on=None):
        self.username = username
        self.email = email
        self.password = password
        self.confirmed = confirmed
        self.confirmed_on = confirmed_on

    def __repr__(self):
        return '<Author {}>'.format(self.username)

author/forms.py
from flask_wtf import FlaskForm
from wtforms import validators, StringField, PasswordField, ValidationError
from wtforms.fields.html5 import EmailField
from werkzeug.security import check_password_hash

from author.models import Author


class LoginForm(FlaskForm):
    email = EmailField('Email Address', [validators.InputRequired(), validators.Email()])
    password = PasswordField('Password', [
        validators.DataRequired(),
        validators.Length(min=8, max=80)
    ])

    def validate(self):
        rv = FlaskForm.validate(self)
        if not rv:
            return False

        author = Author.query.filter_by(
            email=self.email.data
        ).first()

        if author:
            if not check_password_hash(author.password, self.password.data):
                self.password.errors.append('Incorrect email or password')
                return False
            return True
        else:
            self.password.errors.append('Incorrect email or password')


class RegisterForm(FlaskForm):
    username = StringField('User Name', [validators.InputRequired()])
    email = EmailField('Email Address', [validators.InputRequired(), validators.Email(message="Please enter a valid Email.")])
    password = PasswordField('New Password', [
        validators.InputRequired(),
        validators.Length(min=8, max=80)
        ])
    confirm = PasswordField('Repeat Password', [
        validators.EqualTo('password', message='Password must match'),
        ])

    # custom validators -- name of method must be validate_"formfield" -- These check for duplicate email/username's
    # they don't need to be called from anywhere -- wtforms handles everything.
    def validate_email(self, email):
        author = Author.query.filter_by(email=email.data).first()
        if author is not None:
            raise ValidationError('Email already in use, please use a different one.')

    def validate_username(self, username):
        author = Author.query.filter_by(username=username.data).first()
        if author is not None:
            raise ValidationError('Username is already in use, please use a different one.')


class SendPasswordResetForm(FlaskForm):
    email = StringField("Email Address", [validators.InputRequired(), validators.Email(message="Please enter a valid Email.")])


class ResetPasswordForm(FlaskForm):
    password = PasswordField('New Password', [
        validators.InputRequired(),
        validators.Length(min=8, max=80)
    ])
    confirm = PasswordField('Repeat Password', [
        validators.EqualTo('password', message='Password must match'),
    ])


class ChangeUsernameForm(FlaskForm):
    username = StringField('User Name', [validators.InputRequired()])

    def validate_username(self, username):
        author = Author.query.filter_by(username=username.data).first()
        if author is not None:
            raise ValidationError('Username is already in use, please use a different one.')

author/views.py
from flask import Blueprint, render_template, redirect, session, url_for, flash, request
from werkzeug.security import generate_password_hash
from itsdangerous import URLSafeTimedSerializer
from flask_mail import Mail, Message
import datetime
from threading import Thread


author_app = Blueprint('author_app', __name__)

from application import db, create_app
from author.models import Author
from author.forms import RegisterForm, LoginForm, SendPasswordResetForm, ResetPasswordForm
from author.decorators import login_required, already_logged_in


application = create_app()
mail = Mail(application)


@author_app.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        author = Author(
            form.username.data,
            form.email.data,
            hashed_password,
            confirmed=False
        )
        db.session.add(author)
        db.session.commit()

        token = generate_confirmation_token(author.email)
        confirm_url = url_for('.confirm_email', token=token, _external=True)
        html = render_template('author/activate.html', confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(author.email, subject, html)
        flash('A confirmation email has been sent, please check your inbox.', 'success')
        return redirect(url_for('.login'))

    return render_template('author/register.html', form=form)


@author_app.route('/login', methods=('GET', 'POST'))
@already_logged_in
def login():
    form = LoginForm()
    error = None

    if request.method == 'GET' and request.args.get('next'):
        session['next'] = request.args.get('next', None)

    if form.validate_on_submit():
        author = Author.query.filter_by(email=form.email.data).first()
        session['id'] = author.id
        session['username'] = author.username
        if 'next' in session:
            next = session.get('next')
            session.pop('next')
            return redirect(next)
        else:
            flash(f"Welcome {author.username}.", "success")
            return redirect(url_for('blog_app.index'))

    return render_template('author/login.html', form=form, error=error)


@author_app.route('/send_password_reset', methods=["GET", "POST"])
@already_logged_in
def send_password_reset():
    form = SendPasswordResetForm()
    flash('Please enter your email address', 'info')

    if form.validate_on_submit():
        author = Author.query.filter_by(email=form.email.data).first()
        if author:
            token = generate_confirmation_token(author.email)
            confirm_url = url_for('.reset_password', token=token, _external=True)
            html = render_template('author/reset_email.html', confirm_url=confirm_url)
            subject = "Password Reset"
            send_email(author.email, subject, html)

            flash("Thanks, please check your inbox for instructions.", "success")
            return redirect(url_for('.login'))

    return render_template('author/send_password_reset.html', form=form)


@author_app.route('/reset_password/<token>', methods=['GET', 'POST'])
@already_logged_in
def reset_password(token):
    email = confirm_token(token)  # de-serialize the token to retrieve email.
    form = ResetPasswordForm()
    author = Author.query.filter_by(email=email).first_or_404()  # retrieve author using email.
    if email is False:
        flash('The reset link is invalid or has expired, please request another one', 'error')  # check for expired tokens.
        return redirect(url_for('.login'))
    flash(f'Hi {author.username}, please enter a new password.', 'info')
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)  # generate hash from pass form data.
        author.password = hashed_password  # change authors password
        db.session.commit()
        flash("Password successfully reset.", "success")
        return redirect(url_for('.login'))
    return render_template('author/reset_password.html', form=form)


@author_app.route('/logout')
def logout():
    session.pop('id')
    session.pop('username')
    flash('User logged out.', 'success')
    return redirect(url_for('.login'))


@author_app.route('/confirm/<token>')  # users will click unique link, which will pass the token into this view.
def confirm_email(token):
    email = confirm_token(token)  # call confirm function, to retrieve email or False.
    if email is False:
        flash('The confirmation link is invalid or has expired.', 'error')
        return redirect(url_for('blog_app.unconfirmed'))
    author = Author.query.filter_by(email=email).first_or_404()  # query the Author model, searching via email.
    if author.confirmed:
        flash("Account already confirmed.", "success")  # <---- already confirmed message.
    else:
        #  set DB fields confirmed & confirmed on, if user is not yet confirmed.
        author.confirmed = True
        author.confirmed_on = datetime.datetime.now()
        db.session.add(author)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')  # <-- success
    return redirect(url_for('blog_app.index'))  # redirect to index.


@author_app.route('/resend')
@login_required
def resend_confirmation():
    author = Author.query.get(session['id'])
    token = generate_confirmation_token(author.email)
    confirm_url = url_for('.confirm_email', token=token, _external=True)
    html = render_template('author/activate.html', confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(author.email, subject, html)
    flash('A new confirmation email has been sent, please check your inbox.', 'success')
    return redirect(url_for('blog_app.unconfirmed'))


@author_app.route('/profile')
def profile():
    return "profile here"


# generate unique token using users email & secret key / password salt in os.environ
def generate_confirmation_token(email):
    serializer = URLSafeTimedSerializer(application.config['SECRET_KEY'])
    return serializer.dumps(email, salt=application.config['SECURITY_PASSWORD_SALT'])


# pass the token into the serializer to retrieve the users email address or False, if nothing found.
def confirm_token(token, expiration=3600):
    serializer = URLSafeTimedSerializer(application.config['SECRET_KEY'])
    try:
        email = serializer.loads(token,
                                 salt=application.config['SECURITY_PASSWORD_SALT'],
                                 max_age=expiration)
    except:
        return False
    return email


def send_async_email(app, msg):
    with app.app_context():
        mail.send(msg)


def send_email(to, subject, template):
    msg = Message(
        subject,
        recipients=[to],
        html=template,
        sender=application.config['MAIL_DEFAULT_SENDER']
    )
    Thread(target=send_async_email, args=(application, msg)).start()  # creates a job to send the email.

templates/author/activate.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
<head>
<meta name="viewport" content="width=device-width" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Confirm Email</title>


<style type="text/css">
img {
max-width: 100%;
}
body {
-webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; line-height: 1.6em;
}
body {
background-color: #f6f6f6;
}
@media only screen and (max-width: 640px) {
  body {
    padding: 0 !important;
  }
  h1 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h2 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h3 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h4 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h1 {
    font-size: 22px !important;
  }
  h2 {
    font-size: 18px !important;
  }
  h3 {
    font-size: 16px !important;
  }
  .container {
    padding: 0 !important; width: 100% !important;
  }
  .content {
    padding: 0 !important;
  }
  .content-wrap {
    padding: 10px !important;
  }
  .invoice {
    width: 100% !important;
  }
}
</style>
</head>

<body itemscope itemtype="http://schema.org/EmailMessage" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; line-height: 1.6em; background-color: #f6f6f6; margin: 0;" bgcolor="#f6f6f6">

<table class="body-wrap" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; background-color: #f6f6f6; margin: 0;" bgcolor="#f6f6f6"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top"></td>
		<td class="container" width="600" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; display: block !important; max-width: 600px !important; clear: both !important; margin: 0 auto;" valign="top">
			<div class="content" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; max-width: 600px; display: block; margin: 0 auto; padding: 20px;">
				<table class="main" width="100%" cellpadding="0" cellspacing="0" itemprop="action" itemscope itemtype="http://schema.org/ConfirmAction" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; border-radius: 3px; background-color: #fff; margin: 0; border: 1px solid #e9e9e9;" bgcolor="#fff"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-wrap" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 20px;" valign="top">
							<meta itemprop="name" content="Confirm Email" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" /><table width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
										Please confirm your email address by clicking the link below.
								</tr><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" itemprop="handler" itemscope itemtype="http://schema.org/HttpActionHandler" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
										<a type="button" href="{{ confirm_url }}" class=" btn btn-primary" itemprop="url" role="button" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; color: #FFF; text-decoration: none; line-height: 2em; font-weight: bold; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; text-transform: capitalize; background-color: #348eda; margin: 0; border-color: #348eda; border-style: solid; border-width: 10px 20px;">Confirm email address</a>
									</td>
								</tr><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
										&mdash; burgercraft.
									</td>
								</tr></table></td>
					</tr></table><div class="footer" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; clear: both; color: #999; margin: 0; padding: 20px;">
		<td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top"></td>
	</tr></table></body>
</html>

templates/author/login.html
{% extends "base.html" %}

{% block title %}Author Login{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

    <div class="row">

        <div class="offset-md-2 col-md-8">

            {% include '_flashmessages.html' %}

            {#        <h4>Author Login</h4>#}

            {% from "_formhelpers.html" import render_field %}
            <form method="POST" action="{{ url_for('.login') }}" role="form">

                {{ form.hidden_tag() }}

                {{ render_field(form.email, class='form-control') }}
                {{ render_field(form.password, class='form-control') }}

                <button type="submit" class="btn btn-primary">Login</button>
{#                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">Reset Password#}
{#                </button>#}
                <a href="{{ url_for('.send_password_reset') }}" class="btn btn-warning" role="button">Reset Password</a>
            </form>



        </div>

    </div>



{% endblock %}

{#<div class="modal fade" id="myModal" role="dialog">#}
{#                <div class="modal-dialog modal-sm">#}
{##}
{#                    <div class="modal-content">#}
{#                        <h4 class="modal-title">Reset Password</h4>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="modal-body">#}
{#                    <form method="POST" action="{{ url_for('.reset') }}" role="form">#}
{#                        {{ form.hidden_tag() }}#}
{#                        {{ render_field(form.email, class='form-control') }}#}
{#                        <button type="submit" class="btn btn-primary">Submit</button>#}
{#                    </form>#}
{#                </div>#}
{#                <div class="modal-footer">#}
{#                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>#}
{#                </div>#}
{#            </div>#}

templates/author/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">

    <div class="offset-md-2 col-md-8">

{#        <h4>Register.</h4>#}

    {% from "_formhelpers.html" import render_field %}

    <form method="POST" action="{{ url_for('.register')}}" role="form">
        {{ form.hidden_tag()  }}

        {{ render_field(form.username, class='form-control') }}
        {{ render_field(form.email, class='form-control') }}
        {{ render_field(form.password, class='form-control') }}
        {{ render_field(form.confirm, class='form-control') }}

        <button type="submit" class="btn btn-primary">Register</button>
    </form>

    </div>

</div>

{% endblock %}

templates/author/reset_email.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
<head>
<meta name="viewport" content="width=device-width" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Confirm Email</title>


<style type="text/css">
img {
max-width: 100%;
}
body {
-webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; line-height: 1.6em;
}
body {
background-color: #f6f6f6;
}
@media only screen and (max-width: 640px) {
  body {
    padding: 0 !important;
  }
  h1 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h2 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h3 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h4 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h1 {
    font-size: 22px !important;
  }
  h2 {
    font-size: 18px !important;
  }
  h3 {
    font-size: 16px !important;
  }
  .container {
    padding: 0 !important; width: 100% !important;
  }
  .content {
    padding: 0 !important;
  }
  .content-wrap {
    padding: 10px !important;
  }
  .invoice {
    width: 100% !important;
  }
}
</style>
</head>

<body itemscope itemtype="http://schema.org/EmailMessage" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; line-height: 1.6em; background-color: #f6f6f6; margin: 0;" bgcolor="#f6f6f6">

<table class="body-wrap" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; background-color: #f6f6f6; margin: 0;" bgcolor="#f6f6f6"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top"></td>
		<td class="container" width="600" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; display: block !important; max-width: 600px !important; clear: both !important; margin: 0 auto;" valign="top">
			<div class="content" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; max-width: 600px; display: block; margin: 0 auto; padding: 20px;">
				<table class="main" width="100%" cellpadding="0" cellspacing="0" itemprop="action" itemscope itemtype="http://schema.org/ConfirmAction" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; border-radius: 3px; background-color: #fff; margin: 0; border: 1px solid #e9e9e9;" bgcolor="#fff"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-wrap" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 20px;" valign="top">
							<meta itemprop="name" content="Confirm Email" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" /><table width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
										Please click the link below to do your password reset.
								</tr><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" itemprop="handler" itemscope itemtype="http://schema.org/HttpActionHandler" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
										<a type="button" href="{{ confirm_url }}" class=" btn btn-primary" itemprop="url" role="button" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; color: #FFF; text-decoration: none; line-height: 2em; font-weight: bold; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; text-transform: capitalize; background-color: #348eda; margin: 0; border-color: #348eda; border-style: solid; border-width: 10px 20px;">Password reset.</a>
									</td>
								</tr><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
										&mdash; burgercraft.
									</td>
								</tr></table></td>
					</tr></table><div class="footer" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; clear: both; color: #999; margin: 0; padding: 20px;">
		<td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top"></td>
	</tr></table></body>
</html>

templates/author/reset_password.html
{% extends "base.html" %}

{% block title %}Reset Password{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">

<div class="offset-md-2 col-md-8">


        {% include '_flashmessages.html' %}

        {% from "_formhelpers.html" import render_field %}

        <form method="POST" action="" role="form">   <!-- action is empty, we don't want to rebuild the url for /reset_password/<token>, just use it to submit new values for password. -->

            {{ form.hidden_tag() }}

            {{ render_field(form.password, class='form-control')}}
            {{ render_field(form.confirm, class='form-control')}}

            <button type="submit" class="btn btn-primary">Submit</button>
            </form>

    </div>

</div>
{% endblock %}

templates/author/send_password_reset.html
{% extends "base.html" %}

{% block title %}Send Password reset{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">

<div class="offset-md-2 col-md-8">

        {% include '_flashmessages.html' %}

        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('.send_password_reset')}}" role="form">

            {{ form.hidden_tag() }}

            {{ render_field(form.email, class='form-control')}}

            <button type="submit" class="btn btn-primary">Submit</button>

            </form>

    </div>

</div>
{% endblock %}

templates/author/unconfirmed.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

        <div class="offset-md-2 col-md-8 pt-5">

            {% include '_flashmessages.html' %}
            <h2>Hi {{ session.username }},</h2>
            <br>
            <p>Please check your inbox (and your spam folder) - you should have
                received an email with a confirmation link.</p>
            <p>Didn't get the email? <a href="{{ url_for('author_app.resend_confirmation') }}">Resend</a>.</p>
        </div>

{% endblock %}