Blog/forms.py
from flask_wtf import FlaskForm
from wtforms import validators, StringField, TextAreaField, SelectField, FileField
from flask_wtf.file import FileAllowed
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from Blog.models import Category


def categories():
    return Category.query


class PostForm(FlaskForm):
    image = FileField('Image', validators=[
        FileAllowed(['jpg', 'png'], 'We only accept JPG or PNG images')
    ])
    title = StringField('Title', validators=[
            validators.InputRequired(),
            validators.Length(max=80)
        ])
    body = TextAreaField('Content', validators=[validators.InputRequired()])
    category = QuerySelectField('Category', query_factory=categories,
                                allow_blank=True)
    new_category = StringField('New Category')


class CommentForm(FlaskForm):
    comment = TextAreaField('Your Comment', validators=[validators.InputRequired()])

Blog/views.py
from bot import create_neural_network, get_bot_response
from worker import conn
from author.decorators import login_required_check_confirmed, login_required
from author.forms import ResetPasswordForm, ChangeUsernameForm
from Blog.forms import PostForm, CommentForm
from author.models import Author
from Blog.models import Post, Category, Comment
from application import db, create_app
from flask import Blueprint, session, render_template, flash, redirect, url_for, request, jsonify
from slugify import slugify
from werkzeug.security import generate_password_hash
import uuid
from PIL import Image, ExifTags
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
import boto3
import io
import os
from rq import Queue
from rq.job import Job

blog_app = Blueprint('blog_app', __name__)


BUCKET_NAME = os.environ.get('BUCKET_NAME')
limiter = Limiter(
    create_app(),
    key_func=get_remote_address
)
POSTS_PER_PAGE = 5
s3 = boto3.resource('s3')
q = Queue(connection=conn)

model, words, labels = create_neural_network()


@blog_app.route('/send_message', methods=['POST'])
def send_message():
    user_inp = request.form['message']
    bot_text = get_bot_response(model, words, labels, user_inp)
    response_text = {"message": bot_text}
    return jsonify(response_text)


@blog_app.route('/redis')
def redis():
    result = q.enqueue(redis_test)
    return str(result)


@blog_app.route('/results/<job_key>', methods=['GET'])
def results(job_key):
    job = Job.fetch(job_key, connection=conn)

    if job.is_finished:
        return str(job.result), 200
    else:
        return "Nay!", 202


@blog_app.route('/blog')
def index():
    page = int(request.values.get('page', '1'))
    posts = Post.query.filter_by(live=True).order_by(Post.publish_date.desc())\
        .paginate(page, POSTS_PER_PAGE, False)
    return render_template('blog/index.html',
                           posts=posts,
                           title='Latest Posts')


@blog_app.route('/profile', methods=['GET', 'POST'])
@login_required_check_confirmed
def profile():
    author = Author.query.get(session['id'])
    posts = Post.query.filter_by(author_id=author.id).order_by(
        Post.publish_date.desc())[:10]  # Last 10 posts from user

    # forms that will be used for the modals on profile page.
    password_form = ResetPasswordForm()
    username_form = ChangeUsernameForm()

    if password_form.validate_on_submit():
        # generate hash from pass form data.
        hashed_password = generate_password_hash(password_form.password.data)
        author.password = hashed_password  # change authors password
        db.session.commit()
        flash("Password successfully changed.", "success")

    if username_form.validate_on_submit():
        username = username_form.username.data
        author.username = username
        db.session.commit()
        db.session.refresh(author)
        flash("Username successfully changed.", "success")

    return render_template('blog/profile.html', posts=posts, password_form=password_form, username_form=username_form, author=author)


@blog_app.route('/')
def landing():
    return render_template('blog/landing_page.html')


@blog_app.route('/post', methods=('GET', 'POST'))
@login_required_check_confirmed
@limiter.limit("5/hour")
def post():
    form = PostForm()

    if form.validate_on_submit():
        image_id = None

        # create unique ID for image file_name. open image with PIL.
        if form.image.data:
            f = form.image.data
            image_id = str(uuid.uuid4())
            file_name = image_id + '.jpg'
            img = Image.open(f)

            # orientate & resize image
            img = orientate_resize_image(img)

            # Send the Bytes to S3
            img_bytes = io.BytesIO()
            img.save(img_bytes, format='JPEG')
            s3_object = s3.Object(BUCKET_NAME, file_name)
            s3_object.put(
                Body=img_bytes.getvalue(),
                ContentType='image/jpeg'
            )

        # Create new category in DB, if submitted in form.
        if form.new_category.data:
            new_category = Category(form.new_category.data)
            db.session.add(new_category)
            db.session.flush()
            category = new_category
        else:
            category = form.category.data

        author = Author.query.get(session['id'])
        title = form.title.data.strip()
        body = form.body.data.strip()
        post = Post(
            author=author,
            title=title,
            body=body,
            image=image_id,
            category=category
        )

        db.session.add(post)
        db.session.commit()

        slug = slugify(str(post.id) + "-" + post.title)
        post.slug = slug
        db.session.commit()

        flash('Article Posted', 'success')
        return redirect(url_for('.index'))

    return render_template('blog/post.html', form=form, action='new')


# no un-auth comments? all users must be signed up to comment.
@blog_app.route('/posts/<slug>', methods=['GET', 'POST'])
@login_required_check_confirmed
@limiter.limit("20/hour")
def article(slug):
    form = CommentForm()
    post = Post.query.filter_by(slug=slug).first()
    prev_url = request.referrer

    if form.validate_on_submit():
        # query author ID so we can pass username into comment model.
        author = Author.query.get(session['id'])
        comment = Comment(
            author.username,  # username of signed in user.
            form.comment.data  # pull comment data from comment form
        )

        # append comment to post (comments field of the model)
        post.comments.append(comment)
        db.session.add(comment)
        db.session.commit()
        flash("Thank you for taking the time to comment.", 'success')
        return redirect(url_for('.article', slug=slug))

    return render_template('blog/article.html', post=post, form=form, prev_url=prev_url)


@blog_app.route('/edit/<slug>', methods=('GET', 'POST'))
@login_required_check_confirmed
def edit(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    form = PostForm(obj=post)

    if form.validate_on_submit():
        original_image = post.image
        original_title = post.title
        form.populate_obj(post)

        if form.image.data:
            f = form.image.data
            image_id = str(uuid.uuid4())
            file_name = image_id + '.jpg'
            img = Image.open(f)

            # orientate & resize image
            img = orientate_resize_image(img)

            # Send the Bytes to S3
            img_bytes = io.BytesIO()
            img.save(img_bytes, format='JPEG')
            s3_object = s3.Object(BUCKET_NAME, file_name)
            s3_object.put(
                Body=img_bytes.getvalue(),
                ContentType='image/jpeg'
            )

            post.image = image_id

        else:
            post.image = original_image

        if form.new_category.data:
            new_category = Category(form.new_category.data)
            db.session.add(new_category)
            db.session.flush()
            post.category = new_category

        if form.title.data != original_title:
            post.slug = slugify(str(post.id) + '-' + form.title.data)

        # Keeps session open for article view, or it bombs out.
        session.expire_on_commit = False
        db.session.commit()
        flash('Article Edited', 'success')
        return redirect(url_for('.article', slug=post.slug))

    return render_template('blog/post.html', form=form, post=post, action='edit')


@blog_app.route('/delete/<slug>')
@login_required_check_confirmed
def delete(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    post.live = False
    db.session.commit()
    flash('Article deleted', 'success')
    return redirect(url_for('.index'))


@blog_app.route('/categories/<category_id>')
def categories(category_id):
    category = Category.query.filter_by(id=category_id).first_or_404()
    page = int(request.values.get('page', '1'))
    posts = category.posts.filter_by(live=True).order_by(
        Post.publish_date.desc()).paginate(page, POSTS_PER_PAGE, False)
    return render_template('blog/category_posts.html', posts=posts, title=category.name, category_id=category_id)


# route for unconfirmed users. Will redirect to index if already confirmed.
@blog_app.route('/unconfirmed')
@login_required
def unconfirmed():
    if (Author.query.get(session['id'])).confirmed is True:
        return redirect(url_for('.index'))
    return render_template('author/unconfirmed.html')


@blog_app.errorhandler(429)
def ratelimit_handler(e):
    flash("Please do not spam, come back in 1 hour.", 'error')
    return redirect(url_for('.index'))


def orientate_resize_image(img):
    try:
        for orientation in ExifTags.TAGS.keys():
            if ExifTags.TAGS[orientation] == 'Orientation':
                break
        exif = dict(img._getexif().items())

        if exif[orientation] == 3:
            img = img.rotate(180, expand=True)
        elif exif[orientation] == 6:
            img = img.rotate(270, expand=True)
        elif exif[orientation] == 8:
            img = img.rotate(90, expand=True)

    except (AttributeError, KeyError, IndexError):
        # cases: image don't have getexif
        pass

    image_base = 600
    wpercent = (image_base / float(img.size[0]))
    hsize = int((float(img.size[1]) * float(wpercent)))
    img = img.resize((image_base, hsize), Image.ANTIALIAS)

    return img


def redis_test():
    return [x for x in range(1, 10000)]

author/views.py
from flask import Blueprint, render_template, redirect, session, url_for, flash, request
from werkzeug.security import generate_password_hash
from itsdangerous import URLSafeTimedSerializer
from flask_mail import Mail, Message
import datetime
from threading import Thread


author_app = Blueprint('author_app', __name__)

from application import db, create_app
from author.models import Author
from author.forms import RegisterForm, LoginForm, SendPasswordResetForm, ResetPasswordForm
from author.decorators import login_required, already_logged_in


application = create_app()
mail = Mail(application)


@author_app.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        author = Author(
            form.username.data,
            form.email.data,
            hashed_password,
            confirmed=False
        )
        db.session.add(author)
        db.session.commit()

        token = generate_confirmation_token(author.email)
        confirm_url = url_for('.confirm_email', token=token, _external=True)
        html = render_template('author/activate.html', confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(author.email, subject, html)
        flash('A confirmation email has been sent, please check your inbox.', 'success')
        return redirect(url_for('.login'))

    return render_template('author/register.html', form=form)


@author_app.route('/login', methods=('GET', 'POST'))
@already_logged_in
def login():
    form = LoginForm()
    error = None

    if request.method == 'GET' and request.args.get('next'):
        session['next'] = request.args.get('next', None)

    if form.validate_on_submit():
        author = Author.query.filter_by(email=form.email.data).first()
        session['id'] = author.id
        session['username'] = author.username
        if 'next' in session:
            next = session.get('next')
            session.pop('next')
            return redirect(next)
        else:
            flash(f"Welcome {author.username}.", "success")
            return redirect(url_for('blog_app.index'))

    return render_template('author/login.html', form=form, error=error)


@author_app.route('/send_password_reset', methods=["GET", "POST"])
@already_logged_in
def send_password_reset():
    form = SendPasswordResetForm()
    flash('Please enter your email address', 'info')

    if form.validate_on_submit():
        author = Author.query.filter_by(email=form.email.data).first()
        if author:
            token = generate_confirmation_token(author.email)
            confirm_url = url_for('.reset_password', token=token, _external=True)
            html = render_template('author/reset_email.html', confirm_url=confirm_url)
            subject = "Password Reset"
            send_email(author.email, subject, html)

            flash("Thanks, please check your inbox for instructions.", "success")
            return redirect(url_for('.login'))

    return render_template('author/send_password_reset.html', form=form)


@author_app.route('/reset_password/<token>', methods=['GET', 'POST'])
@already_logged_in
def reset_password(token):
    email = confirm_token(token)  # de-serialize the token to retrieve email.
    form = ResetPasswordForm()
    author = Author.query.filter_by(email=email).first_or_404()  # retrieve author using email.
    if email is False:
        flash('The reset link is invalid or has expired, please request another one', 'error')  # check for expired tokens.
        return redirect(url_for('.login'))
    flash(f'Hi {author.username}, please enter a new password.', 'info')
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)  # generate hash from pass form data.
        author.password = hashed_password  # change authors password
        db.session.commit()
        flash("Password successfully reset.", "success")
        return redirect(url_for('.login'))
    return render_template('author/reset_password.html', form=form)


@author_app.route('/logout')
def logout():
    session.pop('id')
    session.pop('username')
    flash('User logged out.', 'success')
    return redirect(url_for('.login'))


@author_app.route('/confirm/<token>')  # users will click unique link, which will pass the token into this view.
def confirm_email(token):
    email = confirm_token(token)  # call confirm function, to retrieve email or False.
    if email is False:
        flash('The confirmation link is invalid or has expired.', 'error')
        return redirect(url_for('blog_app.unconfirmed'))
    author = Author.query.filter_by(email=email).first_or_404()  # query the Author model, searching via email.
    if author.confirmed:
        flash("Account already confirmed.", "success")  # <---- already confirmed message.
    else:
        #  set DB fields confirmed & confirmed on, if user is not yet confirmed.
        author.confirmed = True
        author.confirmed_on = datetime.datetime.now()
        db.session.add(author)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')  # <-- success
    return redirect(url_for('blog_app.index'))  # redirect to index.


@author_app.route('/resend')
@login_required
def resend_confirmation():
    author = Author.query.get(session['id'])
    token = generate_confirmation_token(author.email)
    confirm_url = url_for('.confirm_email', token=token, _external=True)
    html = render_template('author/activate.html', confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(author.email, subject, html)
    flash('A new confirmation email has been sent, please check your inbox.', 'success')
    return redirect(url_for('blog_app.unconfirmed'))


@author_app.route('/profile')
def profile():
    return "profile here"


# generate unique token using users email & secret key / password salt in os.environ
def generate_confirmation_token(email):
    serializer = URLSafeTimedSerializer(application.config['SECRET_KEY'])
    return serializer.dumps(email, salt=application.config['SECURITY_PASSWORD_SALT'])


# pass the token into the serializer to retrieve the users email address or False, if nothing found.
def confirm_token(token, expiration=3600):
    serializer = URLSafeTimedSerializer(application.config['SECRET_KEY'])
    try:
        email = serializer.loads(token,
                                 salt=application.config['SECURITY_PASSWORD_SALT'],
                                 max_age=expiration)
    except:
        return False
    return email


def send_async_email(app, msg):
    with app.app_context():
        mail.send(msg)


def send_email(to, subject, template):
    msg = Message(
        subject,
        recipients=[to],
        html=template,
        sender=application.config['MAIL_DEFAULT_SENDER']
    )
    Thread(target=send_async_email, args=(application, msg)).start()  # creates a job to send the email.

templates/blog/_article_list.html
<link rel="stylesheet" href="{{ url_for('static', filename='css/style0z.css') }}"/>

<div class="post-list">
            {% for post in posts.items %}
            <div class="row post-item pt-3">
                <div class="col-md-9">
                    <h5><a class="text-primary text-uppercase" href="{{ url_for('blog_app.article', slug=post.slug) }}">{{ post.title }}</a></h5>
                    <div class="test">{{ post.body[:220] }}</div>
                    <div class="text-muted">Posted by {{ post.author.username }} | {{
                        post.publish_date.strftime('%d-%m-%Y') }}
                        {% if post.category %}
                        | <a class="text-custom text-uppercase" href="{{ url_for('.categories', category_id=post.category.id) }}">
                            {{ post.category.name }}</a>
                        {% endif %}
                    </div>
                </div>
            <div class="col-md-3">
                {% if post.image %}
                <img src="https://{{ config['REGION'] }}.amazonaws.com/{{ config['BUCKET_NAME'] }}/{{ post.image }}.jpg" class="img-thumbnail" />
                {% endif %}
            </div>
            </div>
            <hr />
            {% endfor %}
        </div>

templates/blog/article.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style0z.css') }}"/>

<div class="row">

    <div class="offset-md-2 col-md-8" >

        {% include '_flashmessages.html' %}

        {% if post.image %}
        <div class="container pt-3">
            <img src="https://{{ config['REGION'] }}.amazonaws.com/{{ config['BUCKET_NAME'] }}/{{ post.image }}.jpg" class="img-fluid" />
        </div>
        {% endif %}

        <h1 class="pt-3">{{ post.title }}</h1>

        <div class="test">{{ post.body|markdown }}</div>

        <div class="text-muted">
            Posted by {{ post.author.username }} | {{ post.publish_date.strftime('%d-%m-%Y') }}
            {% if post.category %}
            | <a href="{{ url_for('.categories', category_id=post.category.id) }}">
                {{ post.category.name }}
            </a>
            {% endif %}
            {% if session.id == post.author.id %}
            - <a href="{{ url_for('.edit', slug=post.slug) }}">Edit</a>
            - <a href="#deleteModal" data-toggle="modal">Delete</a>
            {% endif %}

        </div>
    <hr />
             {% for comment in post.comments %}
            <p>{{ comment.name }}: {{ comment.comment }} | {{ comment.comment_date.strftime('%d-%m-%Y') }}</p>
            {% endfor %}

            {% if session.id %}
            {% from "_formhelpers.html" import render_field %}
            <form method="POST" action="{{ url_for('.article', slug=post.slug) }}" enctype="multipart/form-data"
                      role="form">

            {{ form.hidden_tag() }}
            {{ render_field(form.comment, class='form-control', rows=10) }}
                <a type="button" class="btn btn-primary" href="{{ prev_url }}" role="button">Back</a>
                <button type="submit" class="btn btn-primary">Comment</button>
            </form>
            {% endif %}
    </div>

</div>


<!-- The Modal (confirm deletion) -->
<div class="modal" id="deleteModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Are you sure you want to delete the post "{{ post.title }}"?</h4>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
           <a type="button" class="btn btn-primary" href="{{ url_for('.delete', slug=post.slug) }}" role="button">Yes</a>
           <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>


{% endblock %}

templates/blog/category_posts.html
{% extends "base.html" %}

{% block title %}{{ title }} - {{ config['BLOG_NAME'] }}{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">

    <div class="offset-md-2 col-md-8 pt-5">

    {% include '_flashmessages.html' %}

    <h4>{{ title }}</h4>

    {% include 'blog/_article_list.html' %}

    </div>

</div>

<div class="row">

  <div class="offset-md-2 col-md-8 pt-5">
      {% if posts.has_prev %}
        <a href="{{ url_for('blog_app.categories', category_id=category_id, page=posts.prev_num) }}">&lt;&lt; Newer posts</a>
      {% endif %}
      {% if posts.has_next %}
        <a href="{{ url_for('blog_app.categories', category_id=category_id, page=posts.next_num) }}">Older posts &gt;&gt;</a>
      {% endif %}
  </div>

</div>
{% endblock %}

templates/blog/index.html
{% extends "base.html" %}

{% block title %}{{ title }} - {{ config['BLOG_NAME'] }}{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">

    <div class="offset-md-2 col-md-8 pt-5">

        {% include '_flashmessages.html' %}

        <h4>Posts</h4>

        {% include 'blog/_article_list.html' %}

    </div>

</div>

    <div class="row">

    <div class="offset-md-2 col-md-8 pt-5">
        {% if posts.has_prev %}
        <a href="{{ url_for('blog_app.index', page=posts.prev_num) }}"><i class="fas fa-arrow-left"></i> Newer posts </a>
        {% endif %}
        {% if posts.has_next %}
        <a href="{{ url_for('blog_app.index', page=posts.next_num) }}">Older posts <i class="fas fa-arrow-right"></i></a>
        {% endif %}
    </div>

    </div>

{% endblock %}

templates/blog/landing_page.html
{% extends "base.html" %}

{% block title %}{{ title }} - {{ config['BLOG_NAME'] }}{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}


{#<div class="container-sm">#}
    <div class="col-md-4">
      <div class="thumbnail">
        <a href="https://{{ config['REGION'] }}.amazonaws.com/{{ config['BUCKET_NAME'] }}/mikeller.png" target="_blank">
          <img src="https://{{ config['REGION'] }}.amazonaws.com/{{ config['BUCKET_NAME'] }}/mikeller.png?width=100&height=100" alt="Nature">
          <div class="caption">
          </div>
        </a>
      </div>
    </div>
{#</div>#}


<section class="container-fluid text-right py-1 mt-1" id="contact">
   <h2 class="display-4 pb-4 my-2">Had a standout burger or beer?</h2>
   <p class="lead pb-3">Share with the rest of us at burgercraft =]</p>
    {% if not session.id %}
    <a type="button" class="btn btn-primary" href="{{ url_for('author_app.register') }}" role="button">Register</a>
    {% endif %}

    {% if session.id %}
    <a type="button" class="btn btn-primary" href="{{ url_for('blog_app.index') }}" role="button">Beers & Burgz</a>
    {% endif %}

</section>


{% endblock %}

templates/blog/post.html
{% extends "base.html" %}

{% block title %}Blog Post{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

    <div class="row">

        <div class="offset-md-2 col-md-8">

            {% if action=='new' %}
                <h3>New Post</h3>
            {% else %}
                <h3>Edit Post</h3>
            {% endif %}

            {% from "_formhelpers.html" import render_field %}

            {% if action=="new" %}
                <form method="POST" action="{{ url_for('.post') }}" enctype="multipart/form-data" role="form">
            {% else %}
                <form method="POST" action="{{ url_for('.edit', slug=post.slug) }}" enctype="multipart/form-data"
                      role="form">
            {% endif %}
            {{ form.hidden_tag() }}

            {% if post and post.image %}
            <img src="https://{{ config['REGION'] }}.amazonaws.com/{{ config['BUCKET_NAME'] }}/{{ post.image }}.jpg" class="img-fluid"/>
            {% endif %}

            {{ render_field(form.title, class='form-control') }}
            {{ render_field(form.body, class='form-control', rows=10) }}
            {{ render_field(form.category, class='form-control') }}
            {{ render_field(form.new_category, class='form-control') }}
            {{ render_field(form.image, class='form-inline') }}

            {% if action=='new' %}
                <button type="submit" class="btn btn-primary">Post</button>
            {% else %}
                <button type="submit" class="btn btn-primary">Update</button>
            {% endif %}
            </form>
                </form>

        </div>

    </div>

{% endblock %}

templates/blog/profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

    {% include '_flashmessages.html' %}
    {% from "_formhelpers.html" import render_field %}

<h3>Hi {{ author.username }},</h3>

        <div class="row">
        <div class="offset-md-2 col-md-8">

    <div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
            <button type="button" class="btn-lg btn-primary btn-block" data-toggle="modal" data-target="#passwordModal">Change Password</button>
            <button type="button" class="btn-lg btn-primary btn-block" data-toggle="modal" data-target="#usernameModal">Change Username</button>
        </div>

        <div class="col-lg-6">
        <h4>Your Recent Posts</h4>
            {% for post in posts %}
            <h5><a class="text-primary text-uppercase" href="{{ url_for('blog_app.article', slug=post.slug) }}">{{ post.title }}</a></h5>
            {% endfor %}

        </div>
    </div>
</div>
        </div>
        </div>


<!-- The Modal (Password change) -->
<div class="modal" id="passwordModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Change Password</h4>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
       <form method="POST" action="" role="form">
        {{ password_form.hidden_tag()  }}
           {{ render_field(password_form.password, class='form-control') }}
           {{ render_field(password_form.confirm, class='form-control') }}

           <button type="submit" class="btn btn-primary">Submit</button>

       </form>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>



<!-- The Modal (Username Change) -->
<div class="modal" id="usernameModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Change Username</h4>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <form method="POST" action="" role="form">
        {{ username_form.hidden_tag()  }}
           {{ render_field(username_form.username, class='form-control') }}

            <button type="submit" class="btn btn-primary">Submit</button>

       </form>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>


{% endblock %}

templates/blog/tag_posts.html
{% extends "base.html" %}

{% block title %}{{ title }} - {{ config['BLOG_NAME'] }}{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">

  <div class="offset-md-2 col-md-8 pt-5">

    {% include '_flashmessages.html' %}

    <h4>{{ title }}</h4>

    {% include 'blog/_article_list.html' %}

  </div>

</div>

<div class="row">

  <div class="offset-md-2 col-md-8 pt-5">
      {% if posts.has_prev %}
        <a href="{{ url_for('blog_app.tags', tag=tag, page=posts.prev_num) }}">&lt;&lt; Newer posts</a>
      {% endif %}
      {% if posts.has_next %}
        <a href="{{ url_for('blog_app.tags', tag=tag, page=posts.next_num) }}">Older posts &gt;&gt;</a>
      {% endif %}
  </div>

</div>
{% endblock %}