Blog/views.py
from bot import create_neural_network, get_bot_response
from worker import conn
from author.decorators import login_required_check_confirmed, login_required
from author.forms import ResetPasswordForm, ChangeUsernameForm
from Blog.forms import PostForm, CommentForm
from author.models import Author
from Blog.models import Post, Category, Comment
from application import db, create_app
from flask import Blueprint, session, render_template, flash, redirect, url_for, request, jsonify
from slugify import slugify
from werkzeug.security import generate_password_hash
import uuid
from PIL import Image, ExifTags
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
import boto3
import io
import os
from rq import Queue
from rq.job import Job

blog_app = Blueprint('blog_app', __name__)


BUCKET_NAME = os.environ.get('BUCKET_NAME')
limiter = Limiter(
    create_app(),
    key_func=get_remote_address
)
POSTS_PER_PAGE = 5
s3 = boto3.resource('s3')
q = Queue(connection=conn)

model, words, labels = create_neural_network()


@blog_app.route('/send_message', methods=['POST'])
def send_message():
    user_inp = request.form['message']
    bot_text = get_bot_response(model, words, labels, user_inp)
    response_text = {"message": bot_text}
    return jsonify(response_text)


@blog_app.route('/redis')
def redis():
    result = q.enqueue(redis_test)
    return str(result)


@blog_app.route('/results/<job_key>', methods=['GET'])
def results(job_key):
    job = Job.fetch(job_key, connection=conn)

    if job.is_finished:
        return str(job.result), 200
    else:
        return "Nay!", 202


@blog_app.route('/blog')
def index():
    page = int(request.values.get('page', '1'))
    posts = Post.query.filter_by(live=True).order_by(Post.publish_date.desc())\
        .paginate(page, POSTS_PER_PAGE, False)
    return render_template('blog/index.html',
                           posts=posts,
                           title='Latest Posts')


@blog_app.route('/profile', methods=['GET', 'POST'])
@login_required_check_confirmed
def profile():
    author = Author.query.get(session['id'])
    posts = Post.query.filter_by(author_id=author.id).order_by(
        Post.publish_date.desc())[:10]  # Last 10 posts from user

    # forms that will be used for the modals on profile page.
    password_form = ResetPasswordForm()
    username_form = ChangeUsernameForm()

    if password_form.validate_on_submit():
        # generate hash from pass form data.
        hashed_password = generate_password_hash(password_form.password.data)
        author.password = hashed_password  # change authors password
        db.session.commit()
        flash("Password successfully changed.", "success")

    if username_form.validate_on_submit():
        username = username_form.username.data
        author.username = username
        db.session.commit()
        db.session.refresh(author)
        flash("Username successfully changed.", "success")

    return render_template('blog/profile.html', posts=posts, password_form=password_form, username_form=username_form, author=author)


@blog_app.route('/')
def landing():
    return render_template('blog/landing_page.html')


@blog_app.route('/post', methods=('GET', 'POST'))
@login_required_check_confirmed
@limiter.limit("5/hour")
def post():
    form = PostForm()

    if form.validate_on_submit():
        image_id = None

        # create unique ID for image file_name. open image with PIL.
        if form.image.data:
            f = form.image.data
            image_id = str(uuid.uuid4())
            file_name = image_id + '.jpg'
            img = Image.open(f)

            # orientate & resize image
            img = orientate_resize_image(img)

            # Send the Bytes to S3
            img_bytes = io.BytesIO()
            img.save(img_bytes, format='JPEG')
            s3_object = s3.Object(BUCKET_NAME, file_name)
            s3_object.put(
                Body=img_bytes.getvalue(),
                ContentType='image/jpeg'
            )

        # Create new category in DB, if submitted in form.
        if form.new_category.data:
            new_category = Category(form.new_category.data)
            db.session.add(new_category)
            db.session.flush()
            category = new_category
        else:
            category = form.category.data

        author = Author.query.get(session['id'])
        title = form.title.data.strip()
        body = form.body.data.strip()
        post = Post(
            author=author,
            title=title,
            body=body,
            image=image_id,
            category=category
        )

        db.session.add(post)
        db.session.commit()

        slug = slugify(str(post.id) + "-" + post.title)
        post.slug = slug
        db.session.commit()

        flash('Article Posted', 'success')
        return redirect(url_for('.index'))

    return render_template('blog/post.html', form=form, action='new')


# no un-auth comments? all users must be signed up to comment.
@blog_app.route('/posts/<slug>', methods=['GET', 'POST'])
@login_required_check_confirmed
@limiter.limit("20/hour")
def article(slug):
    form = CommentForm()
    post = Post.query.filter_by(slug=slug).first()
    prev_url = request.referrer

    if form.validate_on_submit():
        # query author ID so we can pass username into comment model.
        author = Author.query.get(session['id'])
        comment = Comment(
            author.username,  # username of signed in user.
            form.comment.data  # pull comment data from comment form
        )

        # append comment to post (comments field of the model)
        post.comments.append(comment)
        db.session.add(comment)
        db.session.commit()
        flash("Thank you for taking the time to comment.", 'success')
        return redirect(url_for('.article', slug=slug))

    return render_template('blog/article.html', post=post, form=form, prev_url=prev_url)


@blog_app.route('/edit/<slug>', methods=('GET', 'POST'))
@login_required_check_confirmed
def edit(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    form = PostForm(obj=post)

    if form.validate_on_submit():
        original_image = post.image
        original_title = post.title
        form.populate_obj(post)

        if form.image.data:
            f = form.image.data
            image_id = str(uuid.uuid4())
            file_name = image_id + '.jpg'
            img = Image.open(f)

            # orientate & resize image
            img = orientate_resize_image(img)

            # Send the Bytes to S3
            img_bytes = io.BytesIO()
            img.save(img_bytes, format='JPEG')
            s3_object = s3.Object(BUCKET_NAME, file_name)
            s3_object.put(
                Body=img_bytes.getvalue(),
                ContentType='image/jpeg'
            )

            post.image = image_id

        else:
            post.image = original_image

        if form.new_category.data:
            new_category = Category(form.new_category.data)
            db.session.add(new_category)
            db.session.flush()
            post.category = new_category

        if form.title.data != original_title:
            post.slug = slugify(str(post.id) + '-' + form.title.data)

        # Keeps session open for article view, or it bombs out.
        session.expire_on_commit = False
        db.session.commit()
        flash('Article Edited', 'success')
        return redirect(url_for('.article', slug=post.slug))

    return render_template('blog/post.html', form=form, post=post, action='edit')


@blog_app.route('/delete/<slug>')
@login_required_check_confirmed
def delete(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    post.live = False
    db.session.commit()
    flash('Article deleted', 'success')
    return redirect(url_for('.index'))


@blog_app.route('/categories/<category_id>')
def categories(category_id):
    category = Category.query.filter_by(id=category_id).first_or_404()
    page = int(request.values.get('page', '1'))
    posts = category.posts.filter_by(live=True).order_by(
        Post.publish_date.desc()).paginate(page, POSTS_PER_PAGE, False)
    return render_template('blog/category_posts.html', posts=posts, title=category.name, category_id=category_id)


# route for unconfirmed users. Will redirect to index if already confirmed.
@blog_app.route('/unconfirmed')
@login_required
def unconfirmed():
    if (Author.query.get(session['id'])).confirmed is True:
        return redirect(url_for('.index'))
    return render_template('author/unconfirmed.html')


@blog_app.errorhandler(429)
def ratelimit_handler(e):
    flash("Please do not spam, come back in 1 hour.", 'error')
    return redirect(url_for('.index'))


def orientate_resize_image(img):
    try:
        for orientation in ExifTags.TAGS.keys():
            if ExifTags.TAGS[orientation] == 'Orientation':
                break
        exif = dict(img._getexif().items())

        if exif[orientation] == 3:
            img = img.rotate(180, expand=True)
        elif exif[orientation] == 6:
            img = img.rotate(270, expand=True)
        elif exif[orientation] == 8:
            img = img.rotate(90, expand=True)

    except (AttributeError, KeyError, IndexError):
        # cases: image don't have getexif
        pass

    image_base = 600
    wpercent = (image_base / float(img.size[0]))
    hsize = int((float(img.size[1]) * float(wpercent)))
    img = img.resize((image_base, hsize), Image.ANTIALIAS)

    return img


def redis_test():
    return [x for x in range(1, 10000)]

author/views.py
from flask import Blueprint, render_template, redirect, session, url_for, flash, request
from werkzeug.security import generate_password_hash
from itsdangerous import URLSafeTimedSerializer
from flask_mail import Mail, Message
import datetime
from threading import Thread


author_app = Blueprint('author_app', __name__)

from application import db, create_app
from author.models import Author
from author.forms import RegisterForm, LoginForm, SendPasswordResetForm, ResetPasswordForm
from author.decorators import login_required, already_logged_in


application = create_app()
mail = Mail(application)


@author_app.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        author = Author(
            form.username.data,
            form.email.data,
            hashed_password,
            confirmed=False
        )
        db.session.add(author)
        db.session.commit()

        token = generate_confirmation_token(author.email)
        confirm_url = url_for('.confirm_email', token=token, _external=True)
        html = render_template('author/activate.html', confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(author.email, subject, html)
        flash('A confirmation email has been sent, please check your inbox.', 'success')
        return redirect(url_for('.login'))

    return render_template('author/register.html', form=form)


@author_app.route('/login', methods=('GET', 'POST'))
@already_logged_in
def login():
    form = LoginForm()
    error = None

    if request.method == 'GET' and request.args.get('next'):
        session['next'] = request.args.get('next', None)

    if form.validate_on_submit():
        author = Author.query.filter_by(email=form.email.data).first()
        session['id'] = author.id
        session['username'] = author.username
        if 'next' in session:
            next = session.get('next')
            session.pop('next')
            return redirect(next)
        else:
            flash(f"Welcome {author.username}.", "success")
            return redirect(url_for('blog_app.index'))

    return render_template('author/login.html', form=form, error=error)


@author_app.route('/send_password_reset', methods=["GET", "POST"])
@already_logged_in
def send_password_reset():
    form = SendPasswordResetForm()
    flash('Please enter your email address', 'info')

    if form.validate_on_submit():
        author = Author.query.filter_by(email=form.email.data).first()
        if author:
            token = generate_confirmation_token(author.email)
            confirm_url = url_for('.reset_password', token=token, _external=True)
            html = render_template('author/reset_email.html', confirm_url=confirm_url)
            subject = "Password Reset"
            send_email(author.email, subject, html)

            flash("Thanks, please check your inbox for instructions.", "success")
            return redirect(url_for('.login'))

    return render_template('author/send_password_reset.html', form=form)


@author_app.route('/reset_password/<token>', methods=['GET', 'POST'])
@already_logged_in
def reset_password(token):
    email = confirm_token(token)  # de-serialize the token to retrieve email.
    form = ResetPasswordForm()
    author = Author.query.filter_by(email=email).first_or_404()  # retrieve author using email.
    if email is False:
        flash('The reset link is invalid or has expired, please request another one', 'error')  # check for expired tokens.
        return redirect(url_for('.login'))
    flash(f'Hi {author.username}, please enter a new password.', 'info')
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)  # generate hash from pass form data.
        author.password = hashed_password  # change authors password
        db.session.commit()
        flash("Password successfully reset.", "success")
        return redirect(url_for('.login'))
    return render_template('author/reset_password.html', form=form)


@author_app.route('/logout')
def logout():
    session.pop('id')
    session.pop('username')
    flash('User logged out.', 'success')
    return redirect(url_for('.login'))


@author_app.route('/confirm/<token>')  # users will click unique link, which will pass the token into this view.
def confirm_email(token):
    email = confirm_token(token)  # call confirm function, to retrieve email or False.
    if email is False:
        flash('The confirmation link is invalid or has expired.', 'error')
        return redirect(url_for('blog_app.unconfirmed'))
    author = Author.query.filter_by(email=email).first_or_404()  # query the Author model, searching via email.
    if author.confirmed:
        flash("Account already confirmed.", "success")  # <---- already confirmed message.
    else:
        #  set DB fields confirmed & confirmed on, if user is not yet confirmed.
        author.confirmed = True
        author.confirmed_on = datetime.datetime.now()
        db.session.add(author)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')  # <-- success
    return redirect(url_for('blog_app.index'))  # redirect to index.


@author_app.route('/resend')
@login_required
def resend_confirmation():
    author = Author.query.get(session['id'])
    token = generate_confirmation_token(author.email)
    confirm_url = url_for('.confirm_email', token=token, _external=True)
    html = render_template('author/activate.html', confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(author.email, subject, html)
    flash('A new confirmation email has been sent, please check your inbox.', 'success')
    return redirect(url_for('blog_app.unconfirmed'))


@author_app.route('/profile')
def profile():
    return "profile here"


# generate unique token using users email & secret key / password salt in os.environ
def generate_confirmation_token(email):
    serializer = URLSafeTimedSerializer(application.config['SECRET_KEY'])
    return serializer.dumps(email, salt=application.config['SECURITY_PASSWORD_SALT'])


# pass the token into the serializer to retrieve the users email address or False, if nothing found.
def confirm_token(token, expiration=3600):
    serializer = URLSafeTimedSerializer(application.config['SECRET_KEY'])
    try:
        email = serializer.loads(token,
                                 salt=application.config['SECURITY_PASSWORD_SALT'],
                                 max_age=expiration)
    except:
        return False
    return email


def send_async_email(app, msg):
    with app.app_context():
        mail.send(msg)


def send_email(to, subject, template):
    msg = Message(
        subject,
        recipients=[to],
        html=template,
        sender=application.config['MAIL_DEFAULT_SENDER']
    )
    Thread(target=send_async_email, args=(application, msg)).start()  # creates a job to send the email.

templates/_flashmessages.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% for category, message in messages %}
        {% if category == 'error' %}
        <div class="{{ category }} alert alert-danger alert-dismissible fade show">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endif %}

        {% if category == 'success' %}
        <div class="{{ category }} alert alert-success alert-dismissible fade show">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endif %}

        {% if category == 'info' %}
        <div class="{{ category }} alert alert-info alert-dismissible fade show">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endif %}

    {% endfor %}
{% endwith %}

templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
  {{ field.label }}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class="text-danger">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
</div>
{% endmacro %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>

    <!-- bootstrap -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

  <body>

    {% block nav %}{% endblock %}

    <div class="container">

    {% block content %}{% endblock %}

      <div class="offset-md-2 col-md-8 pt-5 pb-3">
        <footer>
          <span class="text-muted">&copy; 2019 {{ config['BLOG_NAME'] }}</span>
        </footer>
      </div>

    </div>

    <!-- bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='custom.js')}}"></script>
    <script src="https://cdn.passprotect.io/passprotect.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style0z.css') }}"/>
  </body>
</html>

templates/nav.html
<div class="container pb-3">
    <nav class="navbar navbar-expand-md">
        <a class="navbar-brand" href="{{ url_for('blog_app.landing') }}">
            {{ config['BLOG_NAME'] }}
        </a>
            <ul class="navbar-nav ml-auto navbar-right">
                {% if session.id %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blog_app.index') }}"><i class="fas fa-question">&nbsp;</i>Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blog_app.post') }}"><i class="fas fa-plus">&nbsp;</i>
                            New Post
                        </a>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('author_app.profile') }}"><i class="fas fa-portrait">&nbsp;</i>
                            Profile
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('author_app.logout') }}"><i class="fas fa-sign-out-alt">&nbsp;</i>Logout</a>
                    </li>
                {% else %}
                     <li class="nav-item">
                        <a class="nav-link" href="#chatModal" data-toggle="modal" data-target="#chatModal" ><i class="fas fa-robot">&nbsp;</i>burgercraftBot</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blog_app.index') }}"><i class="fas fa-question">&nbsp;</i>Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('author_app.login') }}"><i class="fas fa-sign-in-alt">&nbsp;</i>Login</a>
                    </li>
                {% endif %}
            </ul>
    </nav>
</div>

<div class="modal" id="chatModal">
              <div class="modal-dialog modal-lg">
                  <div class="modal-content">

                      <!-- Modal Header -->
                      <div class="modal-header">
                          <h4 class="modal-title">Ask & you shall receive</h4>
                      </div>

                      <!-- Modal body -->
                      <div class="modal-body">
                          <div class="container h-100">
                              <div class="row align-items-center h-100">
                                  <div class="col-md-8 col-sm-12 mx-auto">
                                      <div class="h-100 justify-content-center">
                                          <div class="chat-container" style="overflow: auto; max-height: 80vh">
                                              <!-- chat messages -->
                                          </div>
                                          <form id="target">
                                              <input class="input" type="text" value="" placeholder="Enter message..."
                                                     id="input_message"/>
                                              <input type="submit" hidden>
                                          </form>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>

                      <!-- Modal footer -->
                      <div class="modal-footer">
                          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                      </div>
                  </div>
              </div>
          </div>